-- Populate tags_taxonomy table from CSV data
INSERT INTO public.tags_taxonomy (tag, definition, category) VALUES
    ('lead_type:buyer', 'The lead has expressed interest in buying a property', 'lead_type'),
    ('lead_type:seller', 'The lead has expressed interest in selling a property', 'lead_type'),
    ('lead_type:undecided', 'The lead is unsure and just exploring options', 'lead_type'),
    ('buyer_motivation:first_time', 'The lead is purchasing their first property', 'buyer_motivation'),
    ('buyer_motivation:upsizing', 'The lead wants a larger home with more space', 'buyer_motivation'),
    ('buyer_motivation:downsizing', 'The lead wants a smaller home with less maintenance', 'buyer_motivation'),
    ('buyer_motivation:relocating', 'The lead is moving due to work, school, or lifestyle changes', 'buyer_motivation'),
    ('buyer_motivation:investment', 'The lead is buying as an investor', 'buyer_motivation'),
    ('buyer_timeframe:immediate', 'The lead is actively looking for a home right now', 'buyer_timeframe'),
    ('buyer_timeframe:0_3_months', 'The lead wants to buy within the next 3 months', 'buyer_timeframe'),
    ('buyer_timeframe:3_6_months', 'The lead wants to buy in the next 3–6 months', 'buyer_timeframe'),
    ('buyer_timeframe:6_12_months', 'The lead is planning a move within 6–12 months', 'buyer_timeframe'),
    ('buyer_timeframe:long_term', 'The lead is planning to buy in a year or later', 'buyer_timeframe'),
    ('buyer_financing:preapproved', 'The lead has mortgage pre-approval', 'buyer_financing'),
    ('buyer_financing:planning_preapproval', 'The lead is planning to get pre-approval', 'buyer_financing'),
    ('buyer_financing:cash_buyer', 'The lead intends to purchase with cash', 'buyer_financing'),
    ('buyer_financing:needs_guidance', 'The lead is unfamiliar with the mortgage process', 'buyer_financing'),
    ('buyer_home_type:single_family', 'The lead prefers a detached single-family residence', 'buyer_home_type'),
    ('buyer_home_type:condo', 'The lead prefers a condominium', 'buyer_home_type'),
    ('buyer_home_type:townhome', 'The lead prefers a townhouse', 'buyer_home_type'),
    ('buyer_home_type:multifamily', 'The lead prefers a duplex or multi-family property', 'buyer_home_type'),
    ('buyer_home_type:land', 'The lead is interested in vacant land', 'buyer_home_type'),
    ('buyer_home_type:luxury', 'The lead is seeking a luxury property', 'buyer_home_type'),
    ('buyer_home_type:flexible', 'The lead is open to different property types', 'buyer_home_type'),
    ('buyer_location:defined', 'The lead has a specific area chosen', 'buyer_location'),
    ('buyer_location:flexible', 'The lead is open to several neighborhoods', 'buyer_location'),
    ('buyer_location:out_of_area', 'The lead is moving in from another city/state', 'buyer_location'),
    ('appointment_intent:yes', 'Lead agrees to set a buyer consultation', 'appointment_intent'),
    ('appointment_intent:no', 'Lead declines to set an appointment at this time', 'appointment_intent'),
    ('appointment_intent:maybe', 'Lead is open to an appointment but needs times/options', 'appointment_intent'),
    ('appointment_mode:phone', 'Lead prefers phone call for the appointment', 'appointment_mode'),
    ('appointment_mode:video', 'Lead prefers video meeting for the appointment', 'appointment_mode'),
    ('appointment_mode:in_person', 'Lead prefers an in-person meeting', 'appointment_mode'),
    ('appointment_time_pref:morning', 'Lead prefers morning time slots', 'appointment_time_pref'),
    ('appointment_time_pref:afternoon', 'Lead prefers afternoon time slots', 'appointment_time_pref'),
    ('appointment_time_pref:evening', 'Lead prefers evening time slots', 'appointment_time_pref'),
    ('appointment_time_pref:weekend', 'Lead prefers weekends', 'appointment_time_pref'),
    ('appointment_booking_method:text_link', 'Lead wants a booking link sent via SMS', 'appointment_booking_method'),
    ('appointment_booking_method:email_link', 'Lead wants a booking link sent via email', 'appointment_booking_method'),
    ('appointment_booking_method:manual_times', 'Lead prefers the agent to propose specific times', 'appointment_booking_method'),
    ('appointment_candidate:today_pm', 'Lead is open to an appointment today afternoon/evening', 'appointment_candidate'),
    ('appointment_candidate:tomorrow_am', 'Lead is open to an appointment tomorrow morning', 'appointment_candidate'),
    ('appointment_candidate:tomorrow_pm', 'Lead is open to an appointment tomorrow afternoon/evening', 'appointment_candidate'),
    ('appointment_status:confirmed', 'Appointment date/time is confirmed by the lead', 'appointment_status'),
    ('appointment_status:reschedule_requested', 'Lead asks to change the date/time', 'appointment_status'),
    ('appointment_status:unconfirmed', 'Appointment not confirmed by the lead', 'appointment_status'),
    ('buyer_showing_request:yes', 'Lead wants to schedule property showings', 'buyer_showing_request'),
    ('buyer_showing_request:no', 'Lead does not want to schedule showings yet', 'buyer_showing_request'),
    ('buyer_lender_intro:yes', 'Lead requests a lender introduction', 'buyer_lender_intro'),
    ('buyer_lender_intro:has_lender', 'Lead already has a lender', 'buyer_lender_intro'),
    ('buyer_lender_intro:no', 'Lead is not interested in lender intro', 'buyer_lender_intro'),
    ('local_events_interest:yes', 'The lead wants to receive local community event updates', 'local_events_interest'),
    ('local_events_interest:no', 'The lead does not want local community event updates', 'local_events_interest'),
    ('buyer_obstacle:affordability', 'The lead is concerned about affording a home', 'buyer_obstacle'),
    ('buyer_obstacle:need_to_sell', 'The lead must sell a property before buying', 'buyer_obstacle'),
    ('buyer_obstacle:credit', 'The lead is worried about their credit situation', 'buyer_obstacle'),
    ('buyer_obstacle:uncertainty', 'The lead has personal/job instability', 'buyer_obstacle'),
    ('buyer_obstacle:none', 'The lead has no major buying obstacles', 'buyer_obstacle'),
    ('buyer_engagement:home_alerts_yes', 'The lead wants to receive property alerts', 'buyer_engagement'),
    ('buyer_engagement:home_alerts_no', 'The lead does not want property alerts', 'buyer_engagement'),
    ('seller_ownership:confirmed', 'The lead owns the property they want to sell', 'seller_ownership'),
    ('seller_ownership:not_owner', 'The lead does not currently own the property', 'seller_ownership'),
    ('seller_motivation:upsizing', 'The lead wants to sell to purchase a larger home', 'seller_motivation'),
    ('seller_motivation:downsizing', 'The lead wants to sell to move into a smaller home', 'seller_motivation'),
    ('seller_motivation:relocating', 'The lead is moving to another location', 'seller_motivation'),
    ('seller_motivation:financial', 'The lead needs to sell due to financial pressures', 'seller_motivation'),
    ('seller_motivation:investment_cashout', 'The lead is selling an investment property for returns', 'seller_motivation'),
    ('seller_motivation:other', 'The lead has another reason for selling', 'seller_motivation'),
    ('seller_timeframe:immediate', 'The lead wants to list their home right away', 'seller_timeframe'),
    ('seller_timeframe:0_3_months', 'The lead wants to list within 3 months', 'seller_timeframe'),
    ('seller_timeframe:3_6_months', 'The lead plans to sell in 3–6 months', 'seller_timeframe'),
    ('seller_timeframe:6_12_months', 'The lead is planning to sell in 6–12 months', 'seller_timeframe'),
    ('seller_timeframe:long_term', 'The lead is considering selling in a year or more', 'seller_timeframe'),
    ('seller_property_condition:updated', 'The property has recent updates or renovations', 'seller_property_condition'),
    ('seller_property_condition:original', 'The property has not been updated recently', 'seller_property_condition'),
    ('seller_pricing:has_price', 'The lead has a target listing price in mind', 'seller_pricing'),
    ('seller_pricing:needs_guidance', 'The lead needs guidance on pricing', 'seller_pricing'),
    ('seller_appointment_type:pricing_strategy', 'Lead wants a pricing/comps strategy meeting', 'seller_appointment_type'),
    ('seller_appointment_type:skip_pricing', 'Lead declines a pricing session', 'seller_appointment_type'),
    ('seller_appointment_type:listing_prep', 'Lead wants a listing preparation coordination session', 'seller_appointment_type'),
    ('seller_appointment_type:skip_prep', 'Lead declines listing prep coordination', 'seller_appointment_type'),
    ('seller_next_step:buying_after_selling', 'The lead needs to purchase another home after selling', 'seller_next_step'),
    ('seller_next_step:no_buy_needed', 'The lead does not need to buy after selling', 'seller_next_step'),
    ('seller_obstacle:finding_new_home', 'The lead is worried about securing their next home', 'seller_obstacle'),
    ('seller_obstacle:market_conditions', 'The lead is concerned about current real estate market conditions', 'seller_obstacle'),
    ('seller_obstacle:repairs', 'The property needs repairs before sale', 'seller_obstacle'),
    ('seller_obstacle:financial', 'The lead has financial limitations affecting the sale', 'seller_obstacle'),
    ('seller_obstacle:none', 'The lead reports no major obstacles to selling', 'seller_obstacle'),
    ('seller_engagement:cma_yes', 'The lead wants a comparative market analysis', 'seller_engagement'),
    ('seller_engagement:cma_no', 'The lead does not want a comparative market analysis', 'seller_engagement'),
    ('exploring_interest:market', 'The lead is mainly interested in overall real estate market conditions', 'exploring_interest'),
    ('exploring_interest:neighborhoods', 'The lead is curious about local neighborhoods and communities', 'exploring_interest'),
    ('exploring_interest:just_browsing', 'The lead is casually looking with no clear intention yet', 'exploring_interest'),
    ('exploring_future_intent:buyer_future', 'The lead may be interested in buying in the future', 'exploring_future_intent'),
    ('exploring_future_intent:seller_future', 'The lead may be interested in selling in the future', 'exploring_future_intent'),
    ('exploring_future_intent:learning', 'The lead is only gathering information right now', 'exploring_future_intent'),
    ('exploring_timeframe:0_3_months', 'The lead may become active in the next 3 months', 'exploring_timeframe'),
    ('exploring_timeframe:3_6_months', 'The lead may become active in 3–6 months', 'exploring_timeframe'),
    ('exploring_timeframe:6_12_months', 'The lead may become active in 6–12 months', 'exploring_timeframe'),
    ('exploring_timeframe:long_term', 'The lead may become active in a year or more', 'exploring_timeframe'),
    ('exploring_timeframe:unknown', 'The lead is unsure about their future real estate plans', 'exploring_timeframe'),
    ('exploring_engagement:market_updates_yes', 'The lead wants to receive market updates', 'exploring_engagement'),
    ('exploring_engagement:market_updates_no', 'The lead does not want market updates', 'exploring_engagement'),
    ('dnc_status:do_not_contact', 'Lead has requested no further contact via any channel', 'dnc_status'),
    ('dnc_status:reduced_contact', 'Lead requests fewer messages instead of full DNC', 'dnc_status'),
    ('dnc_channel:phone', 'Lead requests no phone calls', 'dnc_channel'),
    ('dnc_channel:sms', 'Lead requests no text messages', 'dnc_channel'),
    ('dnc_channel:email', 'Lead requests no emails', 'dnc_channel'),
    ('dnc_channel:all', 'Lead requests no contact via any channel', 'dnc_channel'),
    ('representation_status:other_agent', 'Lead is already represented by another real estate agent', 'representation_status'),
    ('representation_status:none', 'Lead is not represented by another agent', 'representation_status'),
    ('unsubscribe_scope:marketing_only', 'Lead opts out of marketing communications but allows transactional messages', 'unsubscribe_scope'),
    ('unsubscribe_scope:all', 'Lead opts out of all communications including transactional', 'unsubscribe_scope'),
    ('unsubscribe_scope:none', 'Lead keeps all communications', 'unsubscribe_scope'),
    ('consent_logging:recorded', 'Consent/DNC preference recorded for compliance', 'consent_logging'),
    ('consent_logging:not_recorded', 'Lead does not allow logging of consent/DNC preference', 'consent_logging'),
    ('dnc_confirmation_channel:sms', 'Lead prefers SMS confirmation of DNC settings', 'dnc_confirmation_channel'),
    ('dnc_confirmation_channel:email', 'Lead prefers email confirmation of DNC settings', 'dnc_confirmation_channel'),
    ('dnc_confirmation_channel:none', 'Lead does not need DNC confirmation message', 'dnc_confirmation_channel'),
    ('dnc_reason:frequency', 'Lead opts out due to message frequency', 'dnc_reason'),
    ('dnc_reason:not_interested', 'Lead opts out due to lack of interest', 'dnc_reason'),
    ('dnc_reason:wrong_contact', 'Lead opts out because contact info is incorrect', 'dnc_reason'),
    ('dnc_reason:other_agent', 'Lead opts out because they already have an agent', 'dnc_reason'),
    ('dnc_reason:other', 'Lead opts out for another reason', 'dnc_reason'),
    ('dnc_enforcement:active', 'DNC flags are active; lead should not be contacted on suppressed channels', 'dnc_enforcement'),
    ('compliance_audit:logged', 'Consent/DNC preferences captured for auditability', 'compliance_audit')
ON CONFLICT (tag) DO NOTHING;

-- Total tags inserted: 126