name = "lqs-uat-worker"
main = "worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Environment variables
[vars]
ENVIRONMENT = "UAT"
# OPENAI_API_KEY will be set via wrangler secret put OPENAI_API_KEY
